name: rspec
on:
  push:
    branches:
      - main
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.7
      - name: Install bundler
        run: |
          gem install bundler -v 2.4.22
          bundle install --retry=2
      - name: Run rspec
        run: bundle exec rspec
